<?php

/**
 * @file
 * The module file for media_entity_browser.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function media_entity_browser_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // @todo, detect entity browsers specifically using the MEB view or find
  // another way to attach the library.
  if (strpos($form_id, 'entity_browser') === 0) {
    $form['#attached']['library'][] = 'media_entity_browser/view';
  }
}
